spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: 1234
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: kdt
    
    
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
